const messages = {
   en: {
      accessFailed: "Please check your username and password",
      accessSuccess: "Login successful! Welcome back.",
      unauthorized: "You are not authorized to access this resource.",
      serverError: "An error occurred on the server. Please try again later.",
      userStatus: "User not active,",
      userAccess: "You do not have access to this account. Please contact the administrator.",
      resetPassword: "Please change your password.",
      nodata: "No data available.",
      userToken: "Sorry, Your request could not be processed",
      userSession: "Your session has expired. You can log in again.",
      userAlready: "User already logged in from another device.",
      userIlegal: "Illegal access",
      userAuthenticate: "Failed to authenticate token.",
      insertData: "Data insertion successful",
      failedData: "Insert data failed",
      updateData: "Data update successful",
      deleteData: "Data delete successful",
      userExists: "Username already exists",
      duplicateData: "The data already exists in the system. Please double-check before making any changes",
      passwordSAme: "The password must not be the same as the previous password.",
      resetPasswordSuccess: "Password reset successful.",
      userApproval: "User approval is not available. Please contact the IT Department.",
      postingData: "Data posted successfully",
      coaMax: "This COA block has reached its maximum limit, making further additions impossible.",
      uploadSignature: "To proceed with the posting process, please upload your signature to the system. Thank you.",
      postingCorrect: "Data cannot be posted. Please check again and ensure all information is correct.",
      notBalance: "The following account number is not balanced: {{coa}}",
      successfulData: "Successful Data",
      incomplategoodreceipt: "Incomplete Goods Receipt Data",
      incomplategoodissue: "Incomplete Goods Issue Data",
      closeperiodwarehouse: "Warehouse period closing process for {{period}} completed successfully",
      outOfPeriod: "The date does not match the ongoing period.",
      paymentVoucherCashbak: "Transaction {{codepayment}} cannot be unposted because Cash/Bank {{codecashbank}} has already been created.",
      unpostingData: "Data has been successfully unposted",
      unpostingCorrect: "The data cannot be unposted.",
      deprecationFailed: "The data extraction process related to depreciation has already been carried out.",
      assetNotProcess: "Asset data found that has not gone through the posting process.",
      incomplateCashBank: "Cash/Bank data is not yet completed",
      closingPeriodFailed: "Closing process cannot proceed because the closing for location {{location}} has not been completed.",
      closePeriodMonthly: "Monthly closing process for period {{period}} was successful.",
      beforeClosingPeriod: "Please perform the pre-closing process first before proceeding to the period closing",
      notifBasicSalary: "This employee does not have basic salary data yet.",
      notifBJR: "The Basic Average Yield (BJR) data for this block is not yet available.",
      notifIncentive: "This company does not have any premium data yet. Please complete the premium data first.",
      periodNotAccess: "The accounting period at location {{Location}} has not been created. Please contact the administrator.",
      qtyExceeds: "The order quantity exceeds the requested quantity."

   },
   id: {
      accessFailed: "Silakan periksa nama pengguna dan kata sandi Anda",
      accessSuccess: "Login berhasil! Selamat datang kembali.",
      unauthorized: "Anda tidak diizinkan untuk mengakses sumber daya ini.",
      serverError: "Terjadi kesalahan pada server. Silakan coba lagi nanti.",
      userStatus: "User tidak aktif",
      userAccess: "Akun anda belum ada akses, silahkan hubungi administrator.",
      resetPassword: "Silakan ganti password anda.",
      nodata: "Tidak ada data.",
      userToken: "Maaf, permintaan Anda tidak dapat diproses.",
      userSession: "Sesi anda telah berakhir. Anda dapat login ulang",
      userAlready: "Pengguna sudah masuk dari perangkat lain.",
      userIlegal: "Ilegal akses",
      userAuthenticate: "Gagal mengautentikasi token.",
      insertData: "Insert data berhasil",
      failedData: "Insert data gagal",
      updateData: "Pembaruan data berhasil.",
      deleteData: "Penghapusan data berhasil.",
      userExists: "Nama pengguna sudah ada",
      duplicateData: "Data tersebut sudah ada dalam sistem. Silakan periksa ulang sebelum melakukan perubahan",
      passwordSAme: "Password tidak boleh sama dengan password sebelumnya",
      resetPasswordSuccess: "Reset password berhasil",
      userApproval: "User approval belum tersedia. Silakan hubungi IT Department ",
      postingData: "Data berhasil diposting",
      coaMax: "Kemplok COA ini telah mencapai batas maksimalnya, sehingga tidak memungkinkan untuk penambahan lebih lanjut.",
      uploadSignature: "Untuk melanjutkan proses posting, silakan unggah tanda tangan Anda ke dalam sistem ini. Terima kasih.",
      postingCorrect: "Data tidak dapat diposting. Mohon periksa kembali dan pastikan semua informasi sudah benar.",
      notBalance: "Nomor akun berikut tidak balance: {{coa}}",
      successfulData: "Data Sukses",
      incomplategoodreceipt: "Data Penerimaan Barang Belum Selesai",
      incomplategoodissue: "Data Pengeluaran Barang Belum Selesai",
      closeperiodwarehouse: "Proses tutup buku gudang periode {{period}} berhasil",
      outOfPeriod: "Tanggal tidak sesuai dengan periode yang sedang berlangsung.",
      paymentVoucherCashbak: "Transaksi {{codepayment}} tidak dapat di-unposting karena sudah terbentuk Kas/Bank {{codecashbank}}.",
      unpostingData: "Data berhasil diunposting",
      unpostingCorrect: "Data tidak dapat diunposting.",
      deprecationFailed: "Proses penarikan data terkait penyusutan telah dilaksanakan sebelumnya.",
      assetNotProcess: "Ditemukan data aset yang belum melalui proses posting.",
      incomplateCashBank: "Data kas bank belum selesai",
      closingPeriodFailed: "Proses closing tidak dapat dilanjutkan karena lokasi {{location}} belum diselesaikan proses closing-nya.",
      closePeriodMonthly: "Proses closing bulanan periode {{period}} berhasil.",
      beforeClosingPeriod: "Silakan lakukan pra penutupan terlebih dahulu sebelum melanjutkan ke proses penutupan periode.",
      notifBasicSalary: "Data gaji pokok karyawan ini belum tersedia.",
      notifBJR: "Data Basis Janjang Rata-rata (BJR) untuk blok ini belum tersedia.",
      notifIncentive: "Perusahaan ini belum memiliki data premi. Silakan lengkapi data premi terlebih dahulu.",
      periodNotAccess: "Periode akuntansi pada lokasi {{Location}} belum terbentuk. Silakan hubungi administrator.",
      qtyExceeds: "Jumlah pesanan melebihi jumlah permintaan."

   },
   zh: {
      accessFailed: "请检查您的用户名和密码",
      accessSuccess: "登录成功！欢迎回来。",
      unauthorized: "您无权访问此资源。",
      serverError: "服务器发生错误。请稍后再试。",
      userStatus: "用户未激活",
      userAccess: "你没有访问这个账户的权限。请联系管理员。",
      resetPassword: "请更改您的密码.",
      nodata: "没有数据可用",
      userToken: "抱歉，您的请求无法处理",
      userSession: "您的会话已过期。您可以重新登录",
      userAlready: "用户已从其他设备登录",
      userIlegal: "非法访问",
      userAuthenticate: "令牌验证失败.",
      insertData: "数据插入成功",
      failedData: "插入数据失败",
      updateData: "数据更新成功",
      deleteData: "数据删除成功 ",
      userExists: "用户名已存在",
      duplicateData: "该数据已存在于系统中。请在进行更改前仔细检查",
      passwordSAme: "密码不能与之前的密码相同",
      resetPasswordSuccess: "密码重置成功",
      userApproval: "用户审批不可用。请联系 IT 部门",
      postingData: "数据提交成功",
      coaMax: "该COA块已达到最大限制, 因此无法再进行添加。",
      uploadSignature: "为了继续发布流程，请将您的签名上传至系统。谢谢。",
      postingCorrect: "数据无法提交。请重新检查，并确保所有信息正确。",
      notBalance: "以下账户编号未平衡： {{coa}}",
      successfulData: "成功数据",
      incomplategoodreceipt: "未完成的收货数据",
      incomplategoodissue: "未完成的出库数据",
      closeperiodwarehouse: "仓库{{period}}月结账流程已成功完成",
      outOfPeriod: "日期与当前期间不符。",
      paymentVoucherCashbak: "交易 {{codepayment}} 无法取消过账，因为已生成现金/银行单据 {{codecashbank}}。",
      unpostingData: "数据已成功取消过账",
      unpostingCorrect: "此数据无法取消过账",
      deprecationFailed: "与折旧相关的数据提取过程已在之前执行。",
      assetNotProcess: "发现尚未过账的资产数据。",
      incomplateCashBank: "现金/银行数据尚未完成",
      closingPeriodFailed: "无法继续执行结账流程，因为地点 {{location}} 的结账尚未完成。",
      closePeriodMonthly: "{{period}} 期的月度结账已成功完成。",
      beforeClosingPeriod: "请先执行预结账流程，然后再继续执行结账流程。",
      notifBasicSalary: "该员工尚无基本工资数据。",
      notifBJR: "该区块的基础平均果串 (BJR) 数据尚不可用。",
      notifIncentive: "该公司尚无津贴数据，请先完善津贴信息。",
      periodNotAccess: "位置 {{Location}} 的会计期间尚未建立。请联系管理员。",
      qtyExceeds:"订购数量超过了申请数量。"

   },
};

module.exports = messages;
