// const adm_content = require("./adm_content")
// const adm_content_translations = require("./adm_content_translations")
const adm_company_type = require("./adm_company_type")
const adm_company_type_translations = require("./adm_company_type_translations")
const adm_company = require("./adm_company")
const adm_company_employee_code = require("./adm_company_employee_code")
const hrd_employee = require("./hrd_employee")
const hrd_employee_marital = require("./hrd_employee_marital.js")
const hrd_employee_marital_translations = require("./hrd_employee_marital_translations")
const hrd_employee_salary = require("./hrd_employee_salary")
const hrd_employee_salary_translations = require("./hrd_employee_salary_translations")
const hrd_religion = require("./hrd_religion")
const hrd_religion_translations = require("./hrd_religion_translations")
const hrd_employee_status = require("./hrd_employee_status")
const hrd_employee_status_translations = require("./hrd_employee_status_translations")
const hrd_grade = require("./hrd_grade")
const hrd_grade_translations = require("./hrd_grade_translations")
const hrd_employee_tax = require("./hrd_employee_tax")
const hrd_employee_tax_translations = require("./hrd_employee_tax_translations")
const hrd_education = require("./hrd_education")
const hrd_education_translations = require("./hrd_education_translations")
const hrd_employee_type = require("./hrd_employee_type")
const hrd_employee_type_translations = require("./hrd_employee_type_translations")
const hrd_gender = require("./hrd_gender")
const hrd_gender_translations = require("./hrd_gender_translations")
const hrd_job_title = require("./hrd_job_title")
const hrd_job_title_translations = require("./hrd_job_title_translations")
const hrd_catu = require("./hrd_catu")
const hrd_catu_translations = require("./hrd_catu_translations")
const hrd_department = require("./hrd_department")
const hrd_department_translations = require("./hrd_department_translations")
const hrd_attendace_log = require("./hrd_attendace_log")
const hrd_working_hours = require("./hrd_working_hours")
const hrd_working_hours_translations = require("./hrd_working_hours_translations")
const hrd_employee_assign = require("./hrd_employee_assign")
const adm_authentication = require("./adm_authentication")
const adm_authentication_mobile = require("./adm_authentication_mobile")
const adm_user_login = require("./adm_user_login")
const adm_user_token = require("./adm_user_token")
const adm_menu = require("./adm_menu")
const adm_menu_translations = require("./adm_menu_translations")
const adm_menu_mobile = require("./adm_menu_mobile")
const adm_menu_mobile_translations = require("./adm_menu_mobile_translations")
const adm_approval_type = require("./adm_approval_type")
const adm_approval_type_translations = require("./adm_approval_type_translations")
const adm_approval = require("./adm_approval")
const adm_language = require("./adm_language")
const adm_attendance_machine = require("./adm_attendance_machine")
const fat_accounting_periods = require("./fat_accounting_periods")
const log_item_category = require("./log_item_category")
const log_item_category_translations = require("./log_item_category_translations")
const log_item_master = require("./log_item_master")
const log_purchase_request = require("./log_purchase_request")
const log_purchase_request_detail = require("./log_purchase_request_detail")
const log_purchase_request_approval = require("./log_purchase_request_approval")
const log_partners_type = require("./log_partners_type")
const log_partners_type_translations = require("./log_partners_type_translations")
const log_partners = require("./log_partners")
const log_term_of_payment = require("./log_term_of_payment")
const log_term_of_payment_translations = require("./log_term_of_payment_translations")
const log_receiving_locations = require("./log_receiving_locations")
const log_purchase_request_quotation = require("./log_purchase_request_quotation")
const log_purchase_request_quotation_detail = require("./log_purchase_request_quotation_detail")
const log_purchase_order = require("./log_purchase_order")
const log_purchase_order_detail = require("./log_purchase_order_detail")
const adm_posting = require("./adm_posting")
const adm_posting_type = require("./adm_posting_type")
const adm_posting_type_translations = require("./adm_posting_type_translations")
const adm_signature = require("./adm_signature")
const fat_coa = require("./fat_coa")
const fat_coa_translations = require("./fat_coa_translations")
const log_goods_receipt = require("./log_goods_receipt")
const log_goods_receipt_detail = require("./log_goods_receipt_detail")
const log_goods_receipt_approval = require("./log_goods_receipt_approval")
const log_warehouse = require("./log_warehouse")
const fat_journal = require("./fat_journal")
const fat_balance_monthly = require("./fat_balance_monthly")
const fat_asset_type = require("./fat_asset_type")
const fat_asset_type_translations = require("./fat_asset_type_translations")
const fat_asset_subtype = require("./fat_asset_subtype")
const fat_asset_subtype_translations = require("./fat_asset_subtype_translations")
const fat_asset = require("./fat_asset")
const fat_payment_voucher_type = require("./fat_payment_voucher_type")
const fat_payment_voucher_type_translations = require("./fat_payment_voucher_type_translations")
const adm_activity_type = require("./adm_activity_type")
const adm_activity_type_translations = require("./adm_activity_type_translations")
const adm_activity = require("./adm_activity")
const adm_activity_translations = require("./adm_activity_translations")
const log_goods_issue = require("./log_goods_issue")
const log_goods_issue_detail = require("./log_goods_issue_detail")
const log_goods_issue_approval = require("./log_goods_issue_approval")
const fat_payment_voucher = require("./fat_payment_voucher")
const fat_payment_voucher_detail = require("./fat_payment_voucher_detail")
const fat_account_bank = require("./fat_account_bank")
const fat_cash_bank = require("./fat_cash_bank")
const fat_cash_bank_detail = require("./fat_cash_bank_detail")
const fat_transaction_unposting = require("./fat_transaction_unposting")
const fat_transaction_unposting_translations = require("./fat_transaction_unposting_translations")
const fat_pre_closing_period = require("./fat_pre_closing_period")
const plt_block_master = require("./plt_block_master")
const plt_seed_type = require("./plt_seed_type")
const plt_harvest_penalty_type = require("./plt_harvest_penalty_type")
const plt_harvest_penalty_type_translations = require("./plt_harvest_penalty_type_translations")
const plt_harvest_penalty = require("./plt_harvest_penalty")
const plt_harvest_incentive = require("./plt_harvest_incentive")
const plt_estate_activity = require("./plt_estate_activity")
const plt_estate_activity_detail = require("./plt_estate_activity_detail")
const plt_average_bunch_rate = require("./plt_average_bunch_rate")
const hrd_basic_salary = require("./hrd_basic_salary")
const hrd_holiday  = require("./hrd_holiday.js")
const hrd_natura  = require("./hrd_natura.js")
const plt_estate_activity_penalty  = require("./plt_estate_activity_penalty.js")
const mll_operations  = require("./mll_operations.js")
const mll_operations_repair  = require("./mll_operations_repair.js")

const model = {};

// ADM related models
model.adm_company_type = adm_company_type
model.adm_company_type_translations = adm_company_type_translations
model.adm_company = adm_company
model.adm_company_employee_code = adm_company_employee_code
model.adm_authentication = adm_authentication
model.adm_authentication_mobile = adm_authentication_mobile
model.adm_user_login = adm_user_login
model.adm_user_token = adm_user_token
model.adm_menu = adm_menu
model.adm_menu_translations = adm_menu_translations
model.adm_menu_mobile = adm_menu_mobile
model.adm_menu_mobile_translations = adm_menu_mobile_translations
model.adm_approval_type = adm_approval_type
model.adm_approval_type_translations = adm_approval_type_translations
model.adm_approval = adm_approval
model.adm_language = adm_language
model.adm_attendance_machine = adm_attendance_machine
model.adm_posting = adm_posting
model.adm_posting_type = adm_posting_type
model.adm_posting_type_translations = adm_posting_type_translations
model.adm_signature = adm_signature
model.adm_activity_type = adm_activity_type
model.adm_activity_type_translations = adm_activity_type_translations
model.adm_activity = adm_activity
model.adm_activity_translations = adm_activity_translations

// HRD related models
model.hrd_employee = hrd_employee
model.hrd_employee_marital = hrd_employee_marital
model.hrd_employee_marital_translations = hrd_employee_marital_translations
model.hrd_employee_salary = hrd_employee_salary
model.hrd_employee_salary_translations = hrd_employee_salary_translations
model.hrd_religion = hrd_religion
model.hrd_religion_translations = hrd_religion_translations
model.hrd_employee_status = hrd_employee_status
model.hrd_employee_status_translations = hrd_employee_status_translations
model.hrd_grade = hrd_grade
model.hrd_grade_translations = hrd_grade_translations
model.hrd_employee_tax = hrd_employee_tax
model.hrd_employee_tax_translations = hrd_employee_tax_translations
model.hrd_education = hrd_education
model.hrd_education_translations = hrd_education_translations
model.hrd_employee_type = hrd_employee_type
model.hrd_employee_type_translations = hrd_employee_type_translations
model.hrd_gender = hrd_gender
model.hrd_gender_translations = hrd_gender_translations
model.hrd_job_title = hrd_job_title
model.hrd_job_title_translations = hrd_job_title_translations
model.hrd_catu = hrd_catu
model.hrd_catu_translations = hrd_catu_translations
model.hrd_department = hrd_department
model.hrd_department_translations = hrd_department_translations
model.hrd_attendace_log = hrd_attendace_log
model.hrd_working_hours = hrd_working_hours
model.hrd_employee_assign = hrd_employee_assign
model.hrd_working_hours_translations = hrd_working_hours_translations
model.hrd_basic_salary = hrd_basic_salary
model.hrd_holiday = hrd_holiday
model.hrd_natura = hrd_natura

// FAT related models
model.fat_accounting_periods = fat_accounting_periods
model.fat_coa = fat_coa
model.fat_coa_translations = fat_coa_translations
model.fat_journal = fat_journal
model.fat_balance_monthly = fat_balance_monthly
model.fat_asset_type = fat_asset_type
model.fat_asset_type_translations = fat_asset_type_translations
model.fat_asset_subtype = fat_asset_subtype
model.fat_asset_subtype_translations = fat_asset_subtype_translations
model.fat_asset = fat_asset
model.fat_payment_voucher_type = fat_payment_voucher_type
model.fat_payment_voucher_type_translations = fat_payment_voucher_type_translations
model.fat_payment_voucher = fat_payment_voucher
model.fat_payment_voucher_detail = fat_payment_voucher_detail
model.fat_account_bank = fat_account_bank
model.fat_cash_bank = fat_cash_bank
model.fat_cash_bank_detail = fat_cash_bank_detail
model.fat_transaction_unposting = fat_transaction_unposting
model.fat_transaction_unposting_translations = fat_transaction_unposting_translations
model.fat_pre_closing_period = fat_pre_closing_period

// LOG  related models
model.log_item_category = log_item_category
model.log_item_category_translations = log_item_category_translations
model.log_item_master = log_item_master
model.log_purchase_request = log_purchase_request
model.log_purchase_request_detail = log_purchase_request_detail
model.log_purchase_request_approval = log_purchase_request_approval
model.log_partners_type = log_partners_type
model.log_partners_type_translations = log_partners_type_translations
model.log_partners = log_partners
model.log_term_of_payment = log_term_of_payment
model.log_term_of_payment_translations = log_term_of_payment_translations
model.log_receiving_locations = log_receiving_locations
model.log_purchase_request_quotation = log_purchase_request_quotation
model.log_purchase_request_quotation_detail = log_purchase_request_quotation_detail
model.log_purchase_order = log_purchase_order
model.log_purchase_order_detail = log_purchase_order_detail
model.log_goods_receipt = log_goods_receipt
model.log_goods_receipt_detail = log_goods_receipt_detail
model.log_goods_receipt_approval = log_goods_receipt_approval
model.log_warehouse = log_warehouse
model.log_goods_issue = log_goods_issue
model.log_goods_issue_detail = log_goods_issue_detail
model.log_goods_issue_approval = log_goods_issue_approval

model.plt_block_master = plt_block_master
model.plt_seed_type = plt_seed_type
model.plt_harvest_penalty_type = plt_harvest_penalty_type
model.plt_harvest_penalty_type_translations = plt_harvest_penalty_type_translations
model.plt_harvest_penalty = plt_harvest_penalty
model.plt_harvest_incentive = plt_harvest_incentive
model.plt_estate_activity = plt_estate_activity
model.plt_estate_activity_detail = plt_estate_activity_detail
model.plt_average_bunch_rate = plt_average_bunch_rate
model.plt_estate_activity_penalty = plt_estate_activity_penalty

model.mll_operations = mll_operations
model.mll_operations_repair = mll_operations_repair

module.exports = model;
